## 1. Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

## 2. Load the Raw Dataset

In [ ]:
df = pd.read_csv("atmosync_dataset.csv")

## 3. Initial Exploration

Before touching anything, get a feel for the data: its shape, column names, data
types, and summary statistics. This tells us what cleaning is actually needed
instead of guessing.

In [ ]:
df.head()

,reading_id,container_id,commodity,timestamp,hours_in_transit,temperature_c,humidity_pct,vibration_g,ideal_temp_min_c,ideal_temp_max_c,ideal_humidity_min_pct,ideal_humidity_max_pct,temp_deviation_c,humidity_deviation_pct,origin_port,primary_market,secondary_market,distance_primary_km,distance_secondary_km,quantity_kg,quality_score,shelf_life_hours_remaining,primary_price_per_kg_usd,secondary_price_per_kg_usd,primary_net_value_usd,secondary_net_value_usd,arbitrage_gain_usd,risk_status,recommended_action,cooling_unit_faulty
0,1,CONT-0001,Avocado,2026-07-03 17:23:04.628550,0.0,5.31,88.29,0.220,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.98,2041.8,3.566,3.198,47306.56,42424.67,-4881.89,Normal,Continue to Primary Market,False
1,2,CONT-0001,Avocado,2026-07-03 17:53:04.628550,0.5,5.99,92.25,0.187,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.95,2066.2,3.564,3.197,47280.02,42411.40,-4868.62,Normal,Continue to Primary Market,False
2,3,CONT-0001,Avocado,2026-07-03 18:23:04.628550,1.0,5.10,88.08,0.220,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.93,2040.8,3.563,3.196,47266.76,42398.14,-4868.62,Normal,Continue to Primary Market,False
3,4,CONT-0001,Avocado,2026-07-03 18:53:04.628550,1.5,5.41,88.64,0.248,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.90,2019.8,3.562,3.195,47253.49,42384.87,-4868.62,Normal,Continue to Primary Market,False
4,5,CONT-0001,Avocado,2026-07-03 19:23:04.628550,2.0,5.28,89.30,0.193,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.88,2060.8,3.560,3.194,47226.96,42371.60,-4855.36,Normal,Continue to Primary Market,False

In [ ]:
df.shape

(50000, 30)

In [ ]:
df.columns.tolist()

['reading_id', 'container_id', 'commodity', 'timestamp', 'hours_in_transit', 'temperature_c', 'humidity_pct', 'vibration_g', 'ideal_temp_min_c', 'ideal_temp_max_c', 'ideal_humidity_min_pct', 'ideal_humidity_max_pct', 'temp_deviation_c', 'humidity_deviation_pct', 'origin_port', 'primary_market', 'secondary_market', 'distance_primary_km', 'distance_secondary_km', 'quantity_kg', 'quality_score', 'shelf_life_hours_remaining', 'primary_price_per_kg_usd', 'secondary_price_per_kg_usd', 'primary_net_value_usd', 'secondary_net_value_usd', 'arbitrage_gain_usd', 'risk_status', 'recommended_action', 'cooling_unit_faulty']

In [ ]:
df.dtypes

reading_id                      int64
container_id                      str
commodity                         str
timestamp                         str
hours_in_transit              float64
temperature_c                 float64
humidity_pct                  float64
vibration_g                   float64
ideal_temp_min_c                int64
ideal_temp_max_c                int64
ideal_humidity_min_pct          int64
ideal_humidity_max_pct          int64
temp_deviation_c              float64
humidity_deviation_pct        float64
origin_port                       str
primary_market                    str
secondary_market                  str
distance_primary_km             int64
distance_secondary_km           int64
quantity_kg                     int64
quality_score                 float64
shelf_life_hours_remaining    float64
primary_price_per_kg_usd      float64
secondary_price_per_kg_usd    float64
primary_net_value_usd         float64
secondary_net_value_usd       float64
arbitrage_gain_usd            float64
risk_status                       str
recommended_action                str
cooling_unit_faulty              bool
dtype: object

In [ ]:
df.describe()

,reading_id,hours_in_transit,temperature_c,humidity_pct,vibration_g,ideal_temp_min_c,ideal_temp_max_c,ideal_humidity_min_pct,ideal_humidity_max_pct,temp_deviation_c,humidity_deviation_pct,distance_primary_km,distance_secondary_km,quantity_kg,quality_score,shelf_life_hours_remaining,primary_price_per_kg_usd,secondary_price_per_kg_usd,primary_net_value_usd,secondary_net_value_usd,arbitrage_gain_usd
count,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,24.59565,6.624175,89.974576,0.170556,4.938820,7.346540,87.213600,93.74220,0.391349,0.282092,1825.533000,664.623000,14088.139880,95.605646,1600.255276,2.981790,2.645452,41615.825001,36916.919913,-4698.905087
std,14433.901067,14.43875,5.710725,3.228729,0.188111,5.355794,5.583837,2.483566,2.16957,1.309178,0.985773,283.521822,375.002041,3578.548053,12.127313,776.474637,1.487501,1.311662,23481.561102,20729.788117,3302.703317
min,1.000000,0.00000,-2.710000,73.840000,0.000000,-1.000000,1.000000,85.000000,90.00000,0.000000,0.000000,1400.000000,200.000000,8009.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-21938.430000
25%,12500.750000,12.00000,0.980000,87.870000,0.097000,0.000000,2.000000,85.000000,90.00000,0.000000,0.000000,1600.000000,300.000000,10962.000000,97.340000,1147.100000,1.839000,1.613000,23435.125000,21034.385000,-6533.730000
50%,25000.500000,24.50000,5.590000,90.190000,0.151000,4.000000,7.000000,85.000000,95.00000,0.000000,0.000000,1800.000000,600.000000,14259.000000,98.400000,1703.300000,2.833000,2.519000,37010.970000,32863.870000,-3988.250000
75%,37500.250000,37.00000,11.800000,92.300000,0.206000,10.000000,13.000000,90.000000,95.00000,0.000000,0.000000,2100.000000,900.000000,17247.000000,99.220000,2201.925000,4.139000,3.648000,54472.047500,48498.015000,-2508.800000
max,50000.000000,49.50000,24.170000,99.000000,2.486000,13.000000,15.000000,90.000000,95.00000,9.750000,11.300000,2300.000000,1400.000000,19965.000000,99.980000,2853.200000,6.416000,5.832000,126614.880000,109314.830000,7479.900000

## 4. Check for Duplicates and Missing Values

Duplicate sensor readings would double-count containers in later analysis, and
missing values need to be handled explicitly rather than silently breaking
downstream calculations.

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

reading_id                    0
container_id                  0
commodity                     0
timestamp                     0
hours_in_transit              0
temperature_c                 0
humidity_pct                  0
vibration_g                   0
ideal_temp_min_c              0
ideal_temp_max_c              0
ideal_humidity_min_pct        0
ideal_humidity_max_pct        0
temp_deviation_c              0
humidity_deviation_pct        0
origin_port                   0
primary_market                0
secondary_market              0
distance_primary_km           0
distance_secondary_km         0
quantity_kg                   0
quality_score                 0
shelf_life_hours_remaining    0
primary_price_per_kg_usd      0
secondary_price_per_kg_usd    0
primary_net_value_usd         0
secondary_net_value_usd       0
arbitrage_gain_usd            0
risk_status                   0
recommended_action            0
cooling_unit_faulty           0
dtype: int64

In [ ]:
(df.isnull().sum() / len(df) * 100).round(2)

reading_id                    0.0
container_id                  0.0
commodity                     0.0
timestamp                     0.0
hours_in_transit              0.0
temperature_c                 0.0
humidity_pct                  0.0
vibration_g                   0.0
ideal_temp_min_c              0.0
ideal_temp_max_c              0.0
ideal_humidity_min_pct        0.0
ideal_humidity_max_pct        0.0
temp_deviation_c              0.0
humidity_deviation_pct        0.0
origin_port                   0.0
primary_market                0.0
secondary_market              0.0
distance_primary_km           0.0
distance_secondary_km         0.0
quantity_kg                   0.0
quality_score                 0.0
shelf_life_hours_remaining    0.0
primary_price_per_kg_usd      0.0
secondary_price_per_kg_usd    0.0
primary_net_value_usd         0.0
secondary_net_value_usd       0.0
arbitrage_gain_usd            0.0
risk_status                   0.0
recommended_action            0.0
cooling_unit_faulty           0.0
dtype: float64

**Result:** no duplicate rows and no missing values were found in the raw
export. That's worth confirming explicitly rather than assuming — real-world
sensor feeds usually aren't this clean, so this check stays in the pipeline for
any future data drop.

## 5. Standardize Column Names

Column names are normalized to a consistent `snake_case` format (stripped of
whitespace, lower-cased, spaces replaced with underscores) so every later
reference to a column is predictable.

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [ ]:
df.columns.tolist()

['reading_id', 'container_id', 'commodity', 'timestamp', 'hours_in_transit', 'temperature_c', 'humidity_pct', 'vibration_g', 'ideal_temp_min_c', 'ideal_temp_max_c', 'ideal_humidity_min_pct', 'ideal_humidity_max_pct', 'temp_deviation_c', 'humidity_deviation_pct', 'origin_port', 'primary_market', 'secondary_market', 'distance_primary_km', 'distance_secondary_km', 'quantity_kg', 'quality_score', 'shelf_life_hours_remaining', 'primary_price_per_kg_usd', 'secondary_price_per_kg_usd', 'primary_net_value_usd', 'secondary_net_value_usd', 'arbitrage_gain_usd', 'risk_status', 'recommended_action', 'cooling_unit_faulty']

## 6. Fix the Timestamp Column

The `timestamp` column is read in as plain text by default. Converting it to a
real `datetime` type (and renaming it to the clearer `date_time`) is what makes
time-based sorting, resampling, and plotting possible later on.

In [ ]:
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

In [ ]:
# Confirm the conversion didn't silently fail on any row
df['timestamp'].isnull().sum()

np.int64(0)

In [ ]:
df.rename(columns={'timestamp': 'date_time'}, inplace=True)

In [ ]:
df[['container_id', 'date_time']].head()

  container_id                  date_time
0    CONT-0001 2026-07-03 17:23:04.628550
1    CONT-0001 2026-07-03 17:53:04.628550
2    CONT-0001 2026-07-03 18:23:04.628550
3    CONT-0001 2026-07-03 18:53:04.628550
4    CONT-0001 2026-07-03 19:23:04.628550

## 7. Clean Text Columns

Trailing/leading whitespace in text fields is a common source of "phantom"
categories (e.g. `"Avocado"` vs `"Avocado "` being treated as different groups).
Stripping every text column up front avoids that class of bug.

In [ ]:
text_cols = df.select_dtypes(include='object').columns.tolist()
for col in text_cols:
    df[col] = df[col].str.strip()
text_cols

['container_id', 'commodity', 'origin_port', 'primary_market', 'secondary_market', 'risk_status', 'recommended_action']

## 8. Correct Data Types

* Repeated-category columns (commodity, ports, markets, risk status, recommended
  action) are cast to `category` — this is more memory-efficient and makes
  grouping/plotting cleaner.
* `cooling_unit_faulty` is a true boolean flag and is cast to `bool` explicitly.

In [ ]:
category_cols = [
    "commodity", "origin_port", "primary_market",
    "secondary_market", "risk_status", "recommended_action",
]
for col in category_cols:
    df[col] = df[col].astype("category")

df["cooling_unit_faulty"] = df["cooling_unit_faulty"].astype("bool")
df.dtypes

reading_id                             int64
container_id                             str
commodity                           category
date_time                     datetime64[us]
hours_in_transit                     float64
temperature_c                        float64
humidity_pct                         float64
vibration_g                          float64
ideal_temp_min_c                       int64
ideal_temp_max_c                       int64
ideal_humidity_min_pct                 int64
ideal_humidity_max_pct                 int64
temp_deviation_c                     float64
humidity_deviation_pct               float64
origin_port                         category
primary_market                      category
secondary_market                    category
distance_primary_km                    int64
distance_secondary_km                  int64
quantity_kg                            int64
quality_score                        float64
shelf_life_hours_remaining           float64
primary_price_per_kg_usd             float64
secondary_price_per_kg_usd           float64
primary_net_value_usd                float64
secondary_net_value_usd              float64
arbitrage_gain_usd                   float64
risk_status                         category
recommended_action                  category
cooling_unit_faulty                     bool
dtype: object

## 9. Sort Records Logically

Sensor readings should be ordered by container and then by time — this makes the
data usable for time-series analysis per container (e.g. tracking one shipment's
temperature over its whole transit).

In [ ]:
df = df.sort_values(["container_id", "date_time"]).reset_index(drop=True)
df.head()

,reading_id,container_id,commodity,date_time,hours_in_transit,temperature_c,humidity_pct,vibration_g,ideal_temp_min_c,ideal_temp_max_c,ideal_humidity_min_pct,ideal_humidity_max_pct,temp_deviation_c,humidity_deviation_pct,origin_port,primary_market,secondary_market,distance_primary_km,distance_secondary_km,quantity_kg,quality_score,shelf_life_hours_remaining,primary_price_per_kg_usd,secondary_price_per_kg_usd,primary_net_value_usd,secondary_net_value_usd,arbitrage_gain_usd,risk_status,recommended_action,cooling_unit_faulty
0,1,CONT-0001,Avocado,2026-07-03 17:23:04.628550,0.0,5.31,88.29,0.220,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.98,2041.8,3.566,3.198,47306.56,42424.67,-4881.89,Normal,Continue to Primary Market,False
1,2,CONT-0001,Avocado,2026-07-03 17:53:04.628550,0.5,5.99,92.25,0.187,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.95,2066.2,3.564,3.197,47280.02,42411.40,-4868.62,Normal,Continue to Primary Market,False
2,3,CONT-0001,Avocado,2026-07-03 18:23:04.628550,1.0,5.10,88.08,0.220,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.93,2040.8,3.563,3.196,47266.76,42398.14,-4868.62,Normal,Continue to Primary Market,False
3,4,CONT-0001,Avocado,2026-07-03 18:53:04.628550,1.5,5.41,88.64,0.248,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.90,2019.8,3.562,3.195,47253.49,42384.87,-4868.62,Normal,Continue to Primary Market,False
4,5,CONT-0001,Avocado,2026-07-03 19:23:04.628550,2.0,5.28,89.30,0.193,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.88,2060.8,3.560,3.194,47226.96,42371.60,-4855.36,Normal,Continue to Primary Market,False

## 10. Logical Consistency Checks

Beyond missing values and duplicates, it's worth checking that the data makes
physical sense: ideal temperature ranges should be valid (min < max), and
quantities/prices/transit-time shouldn't be negative.

In [ ]:
print("Rows where ideal_temp_min >= ideal_temp_max:",
      (df["ideal_temp_min_c"] >= df["ideal_temp_max_c"]).sum())
print("Rows with negative hours_in_transit:", (df["hours_in_transit"] < 0).sum())
print("Rows with negative quantity_kg:", (df["quantity_kg"] < 0).sum())
print("Rows with negative primary price:", (df["primary_price_per_kg_usd"] < 0).sum())
print("Rows with negative secondary price:", (df["secondary_price_per_kg_usd"] < 0).sum())

Rows where ideal_temp_min >= ideal_temp_max: 0
Rows with negative hours_in_transit: 0
Rows with negative quantity_kg: 0
Rows with negative primary price: 0
Rows with negative secondary price: 0

All checks pass — the dataset has no logically impossible values, so no rows
need to be dropped or corrected on this basis.

## 11. Engineer a Data Quality Flag

A `data_quality_flag` column is added to make it easy to filter out readings with
significant temperature drift (deviation from the ideal range greater than 3°C)
in later analysis, without deleting any raw data.

In [ ]:
df["data_quality_flag"] = "Normal Reading"
df.loc[df["temp_deviation_c"] > 3, "data_quality_flag"] = "Significant Temperature Drift"
df["data_quality_flag"].value_counts()

data_quality_flag
Normal Reading                   47053
Significant Temperature Drift     2947
Name: count, dtype: int64

## 12. Final Validation

One last pass to confirm the cleaned dataset is complete, correctly typed, and
free of duplicates before saving it.

In [ ]:
df.shape

(50000, 31)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   reading_id                  50000 non-null  int64
 1   container_id                50000 non-null  str
 2   commodity                   50000 non-null  category
 3   date_time                   50000 non-null  datetime64[us]
 4   hours_in_transit            50000 non-null  float64
 5   temperature_c               50000 non-null  float64
 6   humidity_pct                50000 non-null  float64
 7   vibration_g                 50000 non-null  float64
 8   ideal_temp_min_c            50000 non-null  int64
 9   ideal_temp_max_c            50000 non-null  int64
 10  ideal_humidity_min_pct      50000 non-null  int64
 11  ideal_humidity_max_pct      50000 non-null  int64
 12  temp_deviation_c            50000 non-null  float64
 13  humidity_deviation_pct      50000 non-null  float64
 14  origin_port                 50000 non-null  category
 15  primary_market              50000 non-null  category
 16  secondary_market            50000 non-null  category
 17  distance_primary_km         50000 non-null  int64
 18  distance_secondary_km       50000 non-null  int64
 19  quantity_kg                 50000 non-null  int64
 20  quality_score               50000 non-null  float64
 21  shelf_life_hours_remaining  50000 non-null  float64
 22  primary_price_per_kg_usd    50000 non-null  float64
 23  secondary_price_per_kg_usd  50000 non-null  float64
 24  primary_net_value_usd       50000 non-null  float64
 25  secondary_net_value_usd     50000 non-null  float64
 26  arbitrage_gain_usd          50000 non-null  float64
 27  risk_status                 50000 non-null  category
 28  recommended_action          50000 non-null  category
 29  cooling_unit_faulty         50000 non-null  bool
 30  data_quality_flag           50000 non-null  str
dtypes: bool(1), category(6), datetime64[us](1), float64(13), int64(8), str(2)
memory usage: 9.5 MB

In [ ]:
print("Total remaining nulls:", df.isnull().sum().sum())

Total remaining nulls: 0

In [ ]:
print("Remaining duplicate rows:", df.duplicated().sum())

Remaining duplicate rows: 0

In [ ]:
df.head()

,reading_id,container_id,commodity,date_time,hours_in_transit,temperature_c,humidity_pct,vibration_g,ideal_temp_min_c,ideal_temp_max_c,ideal_humidity_min_pct,ideal_humidity_max_pct,temp_deviation_c,humidity_deviation_pct,origin_port,primary_market,secondary_market,distance_primary_km,distance_secondary_km,quantity_kg,quality_score,shelf_life_hours_remaining,primary_price_per_kg_usd,secondary_price_per_kg_usd,primary_net_value_usd,secondary_net_value_usd,arbitrage_gain_usd,risk_status,recommended_action,cooling_unit_faulty,data_quality_flag
0,1,CONT-0001,Avocado,2026-07-03 17:23:04.628550,0.0,5.31,88.29,0.220,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.98,2041.8,3.566,3.198,47306.56,42424.67,-4881.89,Normal,Continue to Primary Market,False,Normal Reading
1,2,CONT-0001,Avocado,2026-07-03 17:53:04.628550,0.5,5.99,92.25,0.187,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.95,2066.2,3.564,3.197,47280.02,42411.40,-4868.62,Normal,Continue to Primary Market,False,Normal Reading
2,3,CONT-0001,Avocado,2026-07-03 18:23:04.628550,1.0,5.10,88.08,0.220,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.93,2040.8,3.563,3.196,47266.76,42398.14,-4868.62,Normal,Continue to Primary Market,False,Normal Reading
3,4,CONT-0001,Avocado,2026-07-03 18:53:04.628550,1.5,5.41,88.64,0.248,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.90,2019.8,3.562,3.195,47253.49,42384.87,-4868.62,Normal,Continue to Primary Market,False,Normal Reading
4,5,CONT-0001,Avocado,2026-07-03 19:23:04.628550,2.0,5.28,89.30,0.193,4,7,85,95,0.0,0.0,Tangier Port (MA),Dubai (AE) - Primary Hub,Muscat (OM) - Secondary Hub,1600,450,13266,99.88,2060.8,3.560,3.194,47226.96,42371.60,-4855.36,Normal,Continue to Primary Market,False,Normal Reading

## 13. Export the Cleaned Dataset

In [ ]:
df.to_csv("atmosync_cleaned.csv", index=False)

In [ ]:
print("Saved atmosync_cleaned.csv —", df.shape[0], "rows x", df.shape[1], "columns")

Saved atmosync_cleaned.csv — 50000 rows x 31 columns